### ISSUE TITLE
Keep comment before link to song in a post and keep original embed window

### ISSUE THREAD

**Issue by Reduvian** [vleeuwenmenno/songwhip-bot#10]
Hi,
Our discord server uses your Songwhip bot and it has been great. We would like to request an enhancement that of whenever someone posts a comment and a link to a song, the bot to keep in the comment when it converts the song into a songwhip post. 

Secondly, when Songwhip converts a user post into its own post, it removes the original embed of the song link, i.e. the YouTube or SoundCloud embed that plays on the discord channel. It would be great if the Songwhip converted post kept the embed to the original link and only added in the streaming services button below it. 

I hope you can make these changes. Cheers

**Comment by vleeuwenmenno** [comment]
Hey, thanks for trying my bot. I'll have a look later if I can add these features. Shouldn't be too hard to add some options so you can toggle this functionality.

I'm currently on holiday out of Europe so I don't have my gear with me so I'll start looking into this in January 10>

**Comment by Reduvian** [comment]
Excellent. Thanks, so much.

**Comment by Reduvian** [comment]
Hey @vleeuwenmenno any update on this man?

**Comment by vleeuwenmenno** [comment]
I'm sorry for the extremely late response, I have made an update just with some other fixes. I will look into a way to add your request too in a somewhat configurable way.

**Comment by vleeuwenmenno** [comment]
As said, I have added a feature. I will be expanding and refactoring the code base a little soon so this feature might change somewhat.

I'll be looking into keeping just the embed later. For now you can opt-in to keep your original message. This is per user basis. `/toggle-keep-message`
