### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by BuzzfeedBlue** [vleeuwenmenno/songwhip-bot#14]
Instead of the single button linking to "streaming services", could you do individual buttons linking to each? You already grab the icons showing where its available so you should have the data to grab each link right?

**Comment by vleeuwenmenno** [comment]
Unfortunately no, Songwhip is used to do this, and they do not supply any of these links. Their API purposefully does this so you have to visit the website. I've been in contact with the owner of this site and there's no way at the moment this will change.
