### ISSUE TITLE
Feature request: global server-level settings?

### ISSUE THREAD

**Issue by ronnix** [vleeuwenmenno/songwhip-bot#15]
If I understand correctly, the `/toggle-xxx` commands allows a user to change the settings that will apply when they share a link.

When a user has not used those commands, then a default behavior will apply.

Would it be possible to get commands to change the default settings at the server-level?

For example, I'd like to set autoresolving mode + keep original message globally, without requiring everyone to use the commands individually.

**Comment by vleeuwenmenno** [comment]
Correct, at the moment it's not server-level. But indeed it would be a nice addition.
I'm planning on doing a big clean-up on the codebase, so I'll take this feature into consideration when doing this, so it can be implemented properly.

**Comment by vleeuwenmenno** [comment]
For reference of what's to come when I get the time to do so: https://github.com/vleeuwenmenno/songwhip-bot/issues/17#issuecomment-1732627728

**Comment by vleeuwenmenno** [comment]
Small update, I started working on upgrades in this PR https://github.com/vleeuwenmenno/songwhip-bot/pull/20

**Comment by vleeuwenmenno** [comment]
I am glad to announce that the bot has been reworked after 16 hours of non-stop hackathon grinding. The whole bot has been rebuild in GoLang and is now ready for more new features.

So feel free to request new features as I am planning to put some more time in it over the next few months.

**Comment by nobuhojimichaan** [comment]
wow great work ' i saw that now original links r not removed ' and embeds don't seem to double '
