### ISSUE TITLE
feature request ' global / server-level settings to turn off the embed and removing original message '

### ISSUE THREAD

**Issue by nobuhojimichaan** [vleeuwenmenno/songwhip-bot#17]
rn i feel there r three aspects of how the bot works that make me hesitate to invite it to my server ' 

1. the user level setting to remove the original message means that most people r unlikely to use it ' 
2. replacing the original message also removes any other txt included with the link ' 
3. discord embeds something for the song twice — first for the user's original message ' second for the song message ' 

the behavior that i would like to see (cc @Podrock) would be as follows ' 

**config**

1. administrator turns on server-level setting to not remove original message ' 
4. administrator turns on server-level setting to disable the embed '

**use case**

1. user drops a link with pre and post txt '
2. message is preserved (not removed) ' includes embed based on the user's original link '
5. songwhip bot responds with button for other streaming services '

desired ' songwhip bot does not include embed ' 
actual ' songwhip bot includes embed ' resulting in a double embed '

**Comment by vleeuwenmenno** [comment]
Your recommendations look are welcome, it's a duplicate to https://github.com/vleeuwenmenno/songwhip-bot/issues/17 though. So I am taking notes, but I am closing this one as there's already a similar issue open for this.

I'm planning once I got time for it to revamp the bot with different levels of config.
The idea is to have 3 config levels.

- Bot hosting config
This should contain dynamically checking for links, so we don't have to re-release the bot once Spotify or whatever decide to change their link URL/structure. (This prevents issues like this https://github.com/vleeuwenmenno/songwhip-bot/issues/16)

- Server level config
This is for admins on discord servers to set up default behaviours.

- User level config
This would be useful for whomever wants to override certain server level configs. (Maybe only in case the server config allows this to be overridden)

**Comment by nobuhojimichaan** [comment]
that makes sense ' ur right ' the major difference  afaict from #15    would be also having a setting for turning off embeds '
